// Code generated by genpackage. DO NOT EDIT.
package strings_gol

import (
	"github.com/ebuckley/gol/lisp"
	strings_ "strings"
)

func init() { lisp.Register("strings", Register) }

// Register adds all exported functions from strings into scope.
func Register(scope *lisp.Scope) {
	scope.Set("clone", lisp.GoFunc(strings_.Clone))
	scope.Set("compare", lisp.GoFunc(strings_.Compare))
	scope.Set("contains", lisp.GoFunc(strings_.Contains))
	scope.Set("contains-any", lisp.GoFunc(strings_.ContainsAny))
	scope.Set("contains-rune", lisp.GoFunc(strings_.ContainsRune))
	scope.Set("count", lisp.GoFunc(strings_.Count))
	scope.Set("cut", lisp.GoFunc(strings_.Cut))
	scope.Set("cut-prefix", lisp.GoFunc(strings_.CutPrefix))
	scope.Set("cut-suffix", lisp.GoFunc(strings_.CutSuffix))
	scope.Set("equal-fold", lisp.GoFunc(strings_.EqualFold))
	scope.Set("fields", lisp.GoFunc(strings_.Fields))
	scope.Set("has-prefix", lisp.GoFunc(strings_.HasPrefix))
	scope.Set("has-suffix", lisp.GoFunc(strings_.HasSuffix))
	scope.Set("index", lisp.GoFunc(strings_.Index))
	scope.Set("index-any", lisp.GoFunc(strings_.IndexAny))
	scope.Set("index-byte", lisp.GoFunc(strings_.IndexByte))
	scope.Set("index-rune", lisp.GoFunc(strings_.IndexRune))
	scope.Set("join", lisp.GoFunc(strings_.Join))
	scope.Set("last-index", lisp.GoFunc(strings_.LastIndex))
	scope.Set("last-index-any", lisp.GoFunc(strings_.LastIndexAny))
	scope.Set("last-index-byte", lisp.GoFunc(strings_.LastIndexByte))
	scope.Set("new-reader", lisp.GoFunc(strings_.NewReader))
	scope.Set("new-replacer", lisp.GoFunc(strings_.NewReplacer))
	scope.Set("repeat", lisp.GoFunc(strings_.Repeat))
	scope.Set("replace", lisp.GoFunc(strings_.Replace))
	scope.Set("replace-all", lisp.GoFunc(strings_.ReplaceAll))
	scope.Set("split", lisp.GoFunc(strings_.Split))
	scope.Set("split-after", lisp.GoFunc(strings_.SplitAfter))
	scope.Set("split-after-n", lisp.GoFunc(strings_.SplitAfterN))
	scope.Set("split-n", lisp.GoFunc(strings_.SplitN))
	scope.Set("title", lisp.GoFunc(strings_.Title))
	scope.Set("to-lower", lisp.GoFunc(strings_.ToLower))
	scope.Set("to-lower-special", lisp.GoFunc(strings_.ToLowerSpecial))
	scope.Set("to-title", lisp.GoFunc(strings_.ToTitle))
	scope.Set("to-title-special", lisp.GoFunc(strings_.ToTitleSpecial))
	scope.Set("to-upper", lisp.GoFunc(strings_.ToUpper))
	scope.Set("to-upper-special", lisp.GoFunc(strings_.ToUpperSpecial))
	scope.Set("to-valid-utf8", lisp.GoFunc(strings_.ToValidUTF8))
	scope.Set("trim", lisp.GoFunc(strings_.Trim))
	scope.Set("trim-left", lisp.GoFunc(strings_.TrimLeft))
	scope.Set("trim-prefix", lisp.GoFunc(strings_.TrimPrefix))
	scope.Set("trim-right", lisp.GoFunc(strings_.TrimRight))
	scope.Set("trim-space", lisp.GoFunc(strings_.TrimSpace))
	scope.Set("trim-suffix", lisp.GoFunc(strings_.TrimSuffix))
}
