// genpackage generates lisp bindings for Go packages.
// Usage: genpackage [-out dir] <pkg> [pkg...]
// Each generated file calls lisp.Register in its init() so a blank import
// activates the package: import _ "github.com/ebuckley/gol/stdlib/strings"
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/importer"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"
)

const fileTmpl = `// Code generated by genpackage. DO NOT EDIT.
package {{.PkgAlias}}_gol

import (
	{{.PkgAlias}}_ "{{.ImportPath}}"
	"github.com/ebuckley/gol/lisp"
)

func init() { lisp.Register("{{.PkgAlias}}", Register) }

// Register adds all exported functions from {{.ImportPath}} into scope.
func Register(scope *lisp.Scope) {
{{- range .Funcs}}
	scope.Set("{{.LispName}}", lisp.GoFunc({{$.PkgAlias}}_.{{.GoName}}))
{{- end}}
}
`

type funcEntry struct {
	GoName   string
	LispName string
}

type pkgData struct {
	PkgAlias   string // last path element, e.g. "strings" or "rand"
	ImportPath string // full import path, e.g. "math/rand"
	Funcs      []funcEntry
}

func main() {
	outDir := flag.String("out", "stdlib", "output directory for generated packages")
	flag.Parse()

	if flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: genpackage [-out dir] <package> [packages...]")
		os.Exit(1)
	}

	fset := token.NewFileSet()
	imp := importer.ForCompiler(fset, "gc", nil)
	tmpl := template.Must(template.New("pkg").Parse(fileTmpl))

	for _, pkgPath := range flag.Args() {
		if err := genPackage(pkgPath, *outDir, imp, tmpl); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", pkgPath, err)
			os.Exit(1)
		}
	}
}

func genPackage(importPath, outDir string, imp types.Importer, tmpl *template.Template) error {
	pkg, err := imp.Import(importPath)
	if err != nil {
		return fmt.Errorf("import: %w", err)
	}

	funcs := exportedFuncs(pkg)
	if len(funcs) == 0 {
		fmt.Fprintf(os.Stderr, "%s: no bindable exported functions, skipping\n", importPath)
		return nil
	}

	// use the last path segment as the alias (e.g. "math/rand" → "rand")
	pkgAlias := pkg.Name()
	data := pkgData{
		PkgAlias:   pkgAlias,
		ImportPath: importPath,
		Funcs:      funcs,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format error (template output follows):\n%s\n%w", buf.String(), err)
	}

	dir := filepath.Join(outDir, pkgAlias)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	outPath := filepath.Join(dir, pkgAlias+"_gol.go")
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d functions)\n", outPath, len(funcs))
	return nil
}

// exportedFuncs returns all exported top-level functions from a package,
// skipping any whose signatures contain unsupported types (chan, map, unsafe).
func exportedFuncs(pkg *types.Package) []funcEntry {
	scope := pkg.Scope()
	var out []funcEntry
	for _, name := range scope.Names() {
		obj, ok := scope.Lookup(name).(*types.Func)
		if !ok || !obj.Exported() {
			continue
		}
		sig := obj.Type().(*types.Signature)
		if sig.Recv() != nil {
			continue // standalone functions only
		}
		if !sigBindable(sig) {
			continue
		}
		out = append(out, funcEntry{
			GoName:   name,
			LispName: camelToKebab(name),
		})
	}
	return out
}

// sigBindable reports whether all parameter and result types can be handled
// by the lisp runtime (no channels, no unsafe.Pointer).
func sigBindable(sig *types.Signature) bool {
	params := sig.Params()
	for i := 0; i < params.Len(); i++ {
		if !typeBindable(params.At(i).Type()) {
			return false
		}
	}
	results := sig.Results()
	for i := 0; i < results.Len(); i++ {
		if !typeBindable(results.At(i).Type()) {
			return false
		}
	}
	return true
}

func typeBindable(t types.Type) bool {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.UnsafePointer, types.Complex64, types.Complex128, types.Uintptr:
			return false
		}
		return true
	case *types.Slice:
		return typeBindable(u.Elem())
	case *types.Pointer:
		return typeBindable(u.Elem())
	case *types.Interface:
		return true
	case *types.Struct:
		return true
	case *types.Named:
		return typeBindable(u.Underlying())
	case *types.Chan, *types.Map, *types.Signature:
		return false
	}
	return true
}

// camelToKebab converts CamelCase to kebab-case: "HasPrefix" → "has-prefix".
func camelToKebab(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) {
			prev := runes[i-1]
			// insert hyphen when transitioning lower→upper or upper→upper+lower
			if unicode.IsLower(prev) || (i+1 < len(runes) && unicode.IsLower(runes[i+1])) {
				b.WriteByte('-')
			}
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}
