// Code generated by genpackage. DO NOT EDIT.
package fmt_gol

import (
	fmt_ "fmt"
	"github.com/ebuckley/gol/lisp"
)

func init() { lisp.Register("fmt", Register) }

// Register adds all exported functions from fmt into scope.
func Register(scope *lisp.Scope) {
	scope.Set("append", lisp.GoFunc(fmt_.Append))
	scope.Set("appendf", lisp.GoFunc(fmt_.Appendf))
	scope.Set("appendln", lisp.GoFunc(fmt_.Appendln))
	scope.Set("errorf", lisp.GoFunc(fmt_.Errorf))
	scope.Set("format-string", lisp.GoFunc(fmt_.FormatString))
	scope.Set("fprint", lisp.GoFunc(fmt_.Fprint))
	scope.Set("fprintf", lisp.GoFunc(fmt_.Fprintf))
	scope.Set("fprintln", lisp.GoFunc(fmt_.Fprintln))
	scope.Set("fscan", lisp.GoFunc(fmt_.Fscan))
	scope.Set("fscanf", lisp.GoFunc(fmt_.Fscanf))
	scope.Set("fscanln", lisp.GoFunc(fmt_.Fscanln))
	scope.Set("print", lisp.GoFunc(fmt_.Print))
	scope.Set("printf", lisp.GoFunc(fmt_.Printf))
	scope.Set("println", lisp.GoFunc(fmt_.Println))
	scope.Set("scan", lisp.GoFunc(fmt_.Scan))
	scope.Set("scanf", lisp.GoFunc(fmt_.Scanf))
	scope.Set("scanln", lisp.GoFunc(fmt_.Scanln))
	scope.Set("sprint", lisp.GoFunc(fmt_.Sprint))
	scope.Set("sprintf", lisp.GoFunc(fmt_.Sprintf))
	scope.Set("sprintln", lisp.GoFunc(fmt_.Sprintln))
	scope.Set("sscan", lisp.GoFunc(fmt_.Sscan))
	scope.Set("sscanf", lisp.GoFunc(fmt_.Sscanf))
	scope.Set("sscanln", lisp.GoFunc(fmt_.Sscanln))
}
